/** \file
 *
 * \brief Generated file for Crc
 *
 * Crc configuration header file.
 *
 * \b Application:        Crc \n
 * \b Target:             see Crc.h for details \n
 * \b Compiler:           see Crc.h for details \n
 * \b Autosar-Vendor-ID:  41 \n
 *
 * \b Module:             Crc \n
 * \b Generator:          Picea Crc V5.0.0-Delivery-Build20 \n
 *
 *      NOTE! This file is generated. Do not edit!
 *
 * \b Changeable-by-user: No \n
 * \b Delivery-File:      No \n
 *
 * \b Module-Owner:       Mecel Picea Team \n
 * \b Location:           Mecel \n
 * \b Phone:              +46 31 720 44 00 \n
 * \b E-Mail:             picea(at)mecel.se \n
 * \b Web:                http://bugzilla.mecel.se/ \n
 *
 * \b Traceability-Info   PICEA* \n
 * \b Classification:     Not classified \n
 * \b Deviations:         None \n
 *
 */

/*============================================================================*
 *
 * Copyright 2012 Mecel AB and Delphi Technologies, Inc., All Rights Reserved
 *
 *============================================================================*/
#ifndef CRC_CFG_H
#define CRC_CFG_H

 /*
 * \reqtrace{DSAR-SDD-CRC-25-2}{CRC022,
 *                               CRC024,
 *                               CRC023,
 *                               CRC006_Conf,
 */


/*============================================================================*\
 *PREPROCESSOR DIRECTIVES
\*============================================================================*/
/* INCLUDE DIRECTIVES FOR STANDARD HEADERS -----------------------------------*/


/* INCLUDE DIRECTIVES FOR OTHER HEADERS --------------------------------------*/


/*
* Major version number of the vendor specific implementation of the module.
* The numbering is vendor specific.
*/
#define CRC_CFG_SW_MAJOR_VERSION       (5)

/*
* Minor version number of the vendor specific implementation of the module.
* The numbering is vendor specific.
*/
#define CRC_CFG_SW_MINOR_VERSION       (0)

/*
* Patch level version number of the vendor specific implementation of the module.
* The numbering is vendor specific.
*/
#define CRC_CFG_SW_PATCH_VERSION       (0)


/** 
* Range of CRC_8_MODE parameter
*/
#define CRC_8_TABLE	(0)

/** 
* Range of CRC_8_MODE parameter
*/
#define CRC_8_RUNTIME	(1)

/** 
* Range of CRC_8_MODE parameter
*/
#define CRC_8_HARDWARE	(2)

/** 
* Range of CRC_8H2F_MODE parameter
*/
#define CRC_8H2F_TABLE	(0)

/** 
* Range of CRC_8H2F_MODE parameter
*/
#define CRC_8H2F_RUNTIME	(1)

/** 
* Range of CRC_8H2F_MODE parameter
*/
#define CRC_8H2F_HARDWARE	(2)

/** 
* Range of CRC_16_MODE parameter
*/
#define CRC_16_TABLE	(0)

/** 
* Range of CRC_16_MODE parameter
*/
#define CRC_16_RUNTIME	(1)

/** 
* Range of CRC_16_MODE parameter
*/
#define CRC_16_HARDWARE	(2)

/** 
* Range of CRC_32_MODE parameter
*/
#define CRC_32_TABLE	(0)

/** 
* Range of CRC_32_MODE parameter
*/
#define CRC_32_RUNTIME	(1)

/** 
* Range of CRC_32_MODE parameter
*/
#define CRC_32_HARDWARE	(2)

/** 
* Parameter setting mode of CRC8 calculation
* \Requirements -->
* \latexonly
* \reqtrace{DSAR-SDD-CRC-43-1}{CRC030_Conf}
* \endlatexonly
*/
#define CRC_8_MODE             CRC_8_TABLE

/** 
* Parameter setting mode of CRC8H2F calculation
* \Requirements -->
* \latexonly
* \reqtrace{DSAR-SDD-CRC-43-1}{CRC031_Conf}
* \endlatexonly
*/
#define CRC_8H2F_MODE             CRC_8H2F_RUNTIME

/** 
* Parameter setting mode of CRC16 calculation
* \Requirements -->
* \latexonly
* \reqtrace{DSAR-SDD-CRC-37-1}{CRC025_Conf}
* \endlatexonly
*/
#define CRC_16_MODE             CRC_16_RUNTIME

/** 
* Parameter setting mode of CRC32 calculation
* \Requirements -->
* \latexonly
* \reqtrace{DSAR-SDD-CRC-38-1}{CRC026_Conf}
* \endlatexonly
*/
#define CRC_32_MODE            CRC_32_RUNTIME

/** 
 /*  ---------------------------------------------------------------------------
 *  This file is generated by Crc source code generator version 4.0.3
 *  ---------------------------------------------------------------------------
\*============================================================================*/
 
#endif /* CRC_CFG_H */
